import { Anchor, Bell, ChevronDown, Compass, CreditCard, LayoutDashboard, Settings, ShieldCheck, Users } from "lucide-react";

const sites = [{ name: "Harbor Point", city: "Annapolis, MD", status: "Active", modules: 3 }, { name: "Severn Landing", city: "Edgewater, MD", status: "Active", modules: 1 }, { name: "Chesapeake Yard", city: "Easton, MD", status: "Setup", modules: 0 }];
const nav = [[LayoutDashboard,"Overview"],[Compass,"Sites"],[Users,"People & roles"],[CreditCard,"Subscription"],[ShieldCheck,"Audit log"],[Settings,"Settings"]] as const;
export default function Home() { return <div className="min-h-screen lg:grid lg:grid-cols-[260px_1fr]">
  <aside className="bg-navy px-5 py-6 text-white lg:min-h-screen"><div className="flex items-center gap-3 text-xl font-bold"><span className="grid size-10 place-items-center rounded-xl bg-ocean"><Anchor size={22}/></span>MarinaOS</div><div className="mt-8 rounded-xl border border-white/10 bg-white/5 p-3"><p className="text-xs uppercase tracking-wider text-white/50">Master account</p><button className="mt-1 flex w-full items-center justify-between font-medium">Atlantic Marina Group <ChevronDown size={16}/></button></div><nav className="mt-7 space-y-1" aria-label="Main navigation">{nav.map(([Icon,label],i)=><a key={label} href="#" className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${i===0?"bg-white/12 text-white":"text-white/65 hover:bg-white/5 hover:text-white"}`}><Icon size={18}/>{label}</a>)}</nav><p className="mt-10 px-3 text-xs leading-5 text-white/45">Sandbox workspace<br/>No live payments or messages</p></aside>
  <main><header className="flex items-center justify-between border-b bg-white px-5 py-4 md:px-9"><div><p className="text-xs font-semibold uppercase tracking-wider text-ocean">Corporate workspace</p><h1 className="text-xl font-bold">Atlantic Marina Group</h1></div><div className="flex items-center gap-3"><button aria-label="Notifications" className="rounded-full border p-2"><Bell size={18}/></button><span className="grid size-9 place-items-center rounded-full bg-foam text-sm font-bold text-ocean">AM</span></div></header>
  <div className="p-5 md:p-9"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h2 className="text-3xl font-bold tracking-tight">Good morning, Alex</h2><p className="mt-1 text-slate-500">A secure view of every marina you’re authorized to manage.</p></div><button className="rounded-lg bg-ocean px-4 py-2.5 text-sm font-semibold text-white shadow-sm">Add site</button></div>
  <section className="mt-8 grid gap-4 md:grid-cols-3"><Metric label="Authorized sites" value="3" note="2 active · 1 in setup"/><Metric label="Monthly subscription" value="$1,197" note="Next invoice Oct 1"/><Metric label="Security status" value="Protected" note="Database policies active" accent/></section>
  <section className="mt-8 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b px-5 py-4"><div><h3 className="font-bold">Your sites</h3><p className="text-sm text-slate-500">Only sites in your authorized scope appear here.</p></div><button className="text-sm font-semibold text-ocean">Manage sites</button></div><div className="divide-y">{sites.map((site,i)=><div className="grid items-center gap-3 px-5 py-4 sm:grid-cols-[1fr_140px_130px_24px]" key={site.name}><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-foam text-ocean"><Anchor size={19}/></span><div><p className="font-semibold">{site.name}</p><p className="text-sm text-slate-500">{site.city}</p></div></div><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-semibold ${i===2?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}`}>{site.status}</span><p className="text-sm text-slate-500">{site.modules} modules on</p><span aria-hidden>›</span></div>)}</div></section>
  <section className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-navy p-6 text-white"><p className="text-sm text-white/60">Foundation checklist</p><h3 className="mt-1 text-xl font-bold">Security first, by design.</h3><ul className="mt-4 space-y-2 text-sm text-white/75"><li>✓ Tenant and site row-level security</li><li>✓ Configurable roles and permissions</li><li>✓ Versioned subscription pricing</li></ul></div><div className="rounded-2xl border bg-white p-6"><p className="text-sm font-semibold text-coral">Action needed</p><h3 className="mt-1 text-xl font-bold">Finish Chesapeake Yard setup</h3><p className="mt-2 text-sm text-slate-500">Assign staff and select the operational modules this site can use.</p><button className="mt-4 text-sm font-bold text-ocean">Continue setup →</button></div></section>
  </div></main></div> }
function Metric({label,value,note,accent=false}:{label:string;value:string;note:string;accent?:boolean}) { return <div className={`rounded-2xl border p-5 shadow-sm ${accent?"border-ocean/20 bg-foam":"bg-white"}`}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div> }
